import SwiftUI
import AppKit

/// Every place the logo appears goes through here.
///
/// The logo is the fish-shaped waveform from the S22 design (2026-09-30,
/// Jakob: Dock + menu-bar icons "改成你设计的样式"). Three renderings share one
/// geometry: `KYMark` (in-app SwiftUI), `statusBarTemplateImage` (menu bar,
/// drawn below), and the app icon in `Assets.xcassets/AppIcon.appiconset`
/// (generated by `scripts/make-app-icon.swift` — re-run it if the mark's
/// proportions change).
enum KYBrand {
    @MainActor static func logo(size: CGFloat) -> some View {
        KYMark(size: size)
    }

    /// The mark's glyph alone (no squircle), as an 18pt template image so
    /// macOS tints it for light/dark menu bars and the highlighted state.
    static var statusBarTemplateImage: NSImage? {
        let image = NSImage(size: NSSize(width: 20, height: 18), flipped: false) { rect in
            guard let context = NSGraphicsContext.current?.cgContext else { return false }
            let glyphBox = rect.insetBy(dx: 1, dy: 1)
            KYMarkGeometry.drawGlyph(in: context, box: glyphBox, ink: NSColor.black.cgColor)
            return true
        }
        image.isTemplate = true
        image.accessibilityDescription = "知鱼录音"
        return image
    }
}

/// Shared proportions of the mark (keep in sync with `scripts/make-app-icon.swift`).
enum KYMarkGeometry {
    static let barHeights: [CGFloat] = [0.18, 0.58, 0.94, 0.64, 0.32]
    static let barWidth: CGFloat = 0.1
    static let gap: CGFloat = 0.075
    static let tailWidth: CGFloat = 0.16
    static let tailHeight: CGFloat = 0.34

    /// Core Graphics rendering of the glyph fitted into `box`, horizontally centered.
    static func drawGlyph(in context: CGContext, box: CGRect, ink: CGColor) {
        let w = box.width, h = box.height
        let bar = w * barWidth, spacing = w * gap, tail = w * tailWidth
        let total = CGFloat(barHeights.count) * (bar + spacing) + tail
        var x = box.midX - total / 2
        context.setFillColor(ink)
        for fraction in barHeights {
            let barHeight = h * fraction
            let rect = CGRect(x: x, y: box.midY - barHeight / 2, width: bar, height: barHeight)
            context.addPath(CGPath(roundedRect: rect, cornerWidth: bar / 2, cornerHeight: bar / 2, transform: nil))
            context.fillPath()
            x += bar + spacing
        }
        let tailRect = CGRect(x: x, y: box.midY - h * tailHeight / 2, width: tail, height: h * tailHeight)
        let path = CGMutablePath()
        path.move(to: CGPoint(x: tailRect.minX, y: tailRect.midY))
        path.addLine(to: CGPoint(x: tailRect.maxX, y: tailRect.maxY))
        path.addQuadCurve(to: CGPoint(x: tailRect.maxX, y: tailRect.minY), control: CGPoint(x: tailRect.maxX - tailRect.width * 0.35, y: tailRect.midY))
        path.closeSubpath()
        context.addPath(path)
        context.fillPath()
    }
}

/// Five waveform bars plus a tail: a recording that is also a fish.
/// `animated` plays M1 ("鱼游入", prototype §06) once on appear — bars spring
/// up in sequence, wobble like live audio, then the tail flicks twice.
struct KYMark: View {
    var size: CGFloat
    var animated: Bool = false
    /// Squircle + gradient behind the glyph. Off → just the glyph in `ink`.
    var showsBackground: Bool = true
    var ink: Color = KYColor.brandInk

    @Environment(\.accessibilityReduceMotion) private var reduceMotion
    @State private var trigger = 0

    private static let barHeights = KYMarkGeometry.barHeights

    var body: some View {
        let glyph = glyphView
        Group {
            if showsBackground {
                RoundedRectangle(cornerRadius: size * 0.27, style: .continuous)
                    .fill(KYColor.brandGradient)
                    .overlay(glyph.frame(width: size * 0.66, height: size * 0.66))
                    .frame(width: size, height: size)
                    .shadow(color: Color(hex: "#3DDBD9")!.opacity(size > 40 ? 0.4 : 0.25), radius: size * 0.18)
            } else {
                glyph.frame(width: size, height: size)
            }
        }
        .onAppear {
            if animated && !reduceMotion { trigger += 1 }
        }
    }

    private var glyphView: some View {
        GeometryReader { proxy in
            let w = proxy.size.width
            let h = proxy.size.height
            let barWidth = w * 0.1
            let gap = w * 0.075
            HStack(alignment: .center, spacing: gap) {
                ForEach(Self.barHeights.indices, id: \.self) { index in
                    Capsule()
                        .fill(ink)
                        .frame(width: barWidth, height: h * Self.barHeights[index])
                        .keyframeAnimator(initialValue: animated && !reduceMotion ? 0.0 : 1.0, trigger: trigger) { view, scale in
                            view.scaleEffect(y: scale)
                        } keyframes: { _ in
                            KeyframeTrack {
                                LinearKeyframe(0, duration: 0.04 + Double(index) * 0.07)
                                SpringKeyframe(1, duration: 0.3, spring: .bouncy)
                                CubicKeyframe(0.45, duration: 0.14)
                                CubicKeyframe(1.1, duration: 0.14)
                                CubicKeyframe(0.7, duration: 0.14)
                                SpringKeyframe(1, duration: 0.3)
                            }
                        }
                }
                FishTail()
                    .fill(ink)
                    .frame(width: w * 0.16, height: h * 0.34)
                    .keyframeAnimator(initialValue: TailState(rest: !(animated && !reduceMotion)), trigger: trigger) { view, state in
                        view
                            .rotationEffect(.degrees(state.angle), anchor: .leading)
                            .offset(x: state.offset)
                            .opacity(state.opacity)
                    } keyframes: { _ in
                        KeyframeTrack(\.opacity) {
                            LinearKeyframe(0, duration: 0.5)
                            LinearKeyframe(1, duration: 0.15)
                        }
                        KeyframeTrack(\.offset) {
                            LinearKeyframe(w * 0.2, duration: 0.5)
                            SpringKeyframe(0, duration: 0.3)
                        }
                        KeyframeTrack(\.angle) {
                            LinearKeyframe(0, duration: 0.75)
                            CubicKeyframe(22, duration: 0.12)
                            CubicKeyframe(-22, duration: 0.14)
                            CubicKeyframe(14, duration: 0.12)
                            SpringKeyframe(0, duration: 0.3)
                        }
                    }
            }
            .frame(width: w, height: h)
        }
    }

    private struct TailState {
        var angle: Double = 0
        var offset: CGFloat = 0
        var opacity: Double = 1

        init(rest: Bool) {
            opacity = rest ? 1 : 0
        }
    }
}

/// A forked tail pointing right (the fish swims left, toward the waveform).
private struct FishTail: Shape {
    func path(in rect: CGRect) -> Path {
        var path = Path()
        path.move(to: CGPoint(x: rect.minX, y: rect.midY))
        path.addLine(to: CGPoint(x: rect.maxX, y: rect.minY))
        path.addQuadCurve(to: CGPoint(x: rect.maxX, y: rect.maxY), control: CGPoint(x: rect.maxX - rect.width * 0.35, y: rect.midY))
        path.closeSubpath()
        return path
    }
}

#Preview {
    HStack(spacing: 24) {
        KYMark(size: 28)
        KYMark(size: 96, animated: true)
        KYMark(size: 22, showsBackground: false, ink: .primary)
    }
    .padding(40)
}
